version: '3'

services:
  api:
    build: .
    command: >
      bash -c "chmod +x ./wait-for-it.sh
      && ./wait-for-it.sh db:5432 -t 0
      -- python manage.py runserver 0.0.0.0:8080
      "

    container_name: django_api

    volumes:
      - .:/code

    ports:
      - "8080:8080"
      - "80:80"
