# Generated by Django 3.1.3 on 2020-12-17 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('purchase_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_phone', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boleto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('boleto_number', models.IntegerField(blank=True, null=True)),
                ('boleto_due_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=500, null=True)),
                ('free_shipping', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AO', 'Aguardando Pedido'), ('AP', 'Aguardando Pagamento'), ('AS', 'Aguardando Envio'), ('AF', 'Aguardando Processamento'), ('F', 'Processado'), ('C', 'Cancelado'), ('FO', 'Pedidos Falhadas')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('gid', models.CharField(max_length=70, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.CharField(max_length=255)),
                ('free_shipping', models.BooleanField(default=False)),
                ('shopify_name', models.CharField(max_length=255, unique=True)),
                ('shopify_key', models.CharField(max_length=255)),
                ('working', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShopee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('proxy', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('proxy_login', models.CharField(max_length=255)),
                ('proxy_password', models.IntegerField()),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('last_free_shipping_purchase', models.DateTimeField(null=True)),
                ('last_purchase', models.DateTimeField(null=True)),
                ('user_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopeeUsers', to='shopee.usershop')),
            ],
        ),
        migrations.CreateModel(
            name='UserShopeeError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('user_shopee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopeeUsersErros', to='shopee.usershopee')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('gid', models.CharField(max_length=70, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('product_shopify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVariants', to='shopee.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductShopee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopee_url', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.IntegerField()),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('option_name', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=500, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVariantsShopee', to='shopee.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('src', models.CharField(blank=True, max_length=500, null=True)),
                ('product_shopify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopifyProductImages', to='shopee.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userShopProductsShopify', to='shopee.usershop'),
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderLineItens', to='shopee.order')),
                ('product_shopify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopifyProducts', to='shopee.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userShopOrders', to='shopee.usershop'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_shopee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrders', to='shopee.usershopee'),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('user_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopee.usershop')),
            ],
        ),
    ]
