# Generated by Django 3.1.3 on 2020-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
