# Generated by Django 3.1.3 on 2020-12-27 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0006_usershopee_spc_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_shopify',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shopifyVariants', to='shopee.productvariant'),
            preserve_default=False,
        ),
    ]
