# Generated by Django 3.0.8 on 2020-12-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0008_order_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
