# Generated by Django 3.0.8 on 2020-12-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0010_auto_20201228_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_shopee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrders', to='shopee.UserShopee'),
        ),
    ]
