# Generated by Django 3.0.8 on 2020-12-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0011_auto_20201228_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usershopee',
            name='proxy_password',
            field=models.CharField(max_length=255),
        ),
    ]
