# Generated by Django 3.0.8 on 2020-12-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0012_auto_20201229_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchase_url',
            new_name='shopee_checkout_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.CreateModel(
            name='OrderPurchase',
            fields=[
                ('shopeeOrderId', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('9', 'A Pagar'), ('7', 'A Enviar'), ('8', 'A Receber'), ('3', 'Concluído'), ('4', 'Cancelado')], max_length=1)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderPurchases', to='shopee.Order')),
            ],
        ),
    ]
