# Generated by Django 3.0.8 on 2021-01-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0013_auto_20201230_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpurchase',
            name='user_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userShopOrderPurchases', to='shopee.UserShop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='user_shopee',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrderPurchases', to='shopee.UserShopee'),
            preserve_default=False,
        ),
    ]
