# Generated by Django 3.0.8 on 2021-01-01 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0014_auto_20210101_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='boleto_due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
