# Generated by Django 3.0.8 on 2021-01-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0015_auto_20210101_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpurchase',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderpurchase',
            old_name='shopeeOrderId',
            new_name='shopee_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_shopee',
        ),
    ]
