# Generated by Django 3.1.3 on 2021-01-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0016_auto_20210101_2142'),
        ('shopee', '0010_auto_20201231_1508'),
    ]

    operations = [
    ]
