# Generated by Django 3.1.3 on 2021-01-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0019_auto_20210102_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='shopify_shared_secret',
            field=models.CharField(default='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', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('api_version', models.CharField(blank=True, max_length=255, null=True)),
                ('user_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='shopee.usershop')),
            ],
        ),
    ]
