# Generated by Django 3.1.3 on 2021-01-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0020_auto_20210104_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='working_admin',
            field=models.BooleanField(default=True),
        ),
    ]
