# Generated by Django 3.1.3 on 2021-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0024_auto_20210108_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='deactivate_status',
            field=models.CharField(blank=True, choices=[('IL', 'Login incorreto'), ('IP', 'Proxy incorreta'), ('IT', 'Token inválido'), ('TE', 'Erro ao finalizar transação'), ('M', 'Manual')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
