# Generated by Django 3.1.3 on 2021-01-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0025_auto_20210108_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpurchase',
            name='shopee_product_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='shopee_product_variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
