# Generated by Django 3.1.3 on 2021-01-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0028_order_error_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
