# Generated by Django 3.1.3 on 2021-01-14 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0029_order_canceled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPurchaseLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopee_order_id', models.CharField(blank=True, max_length=70, null=True)),
                ('status', models.CharField(choices=[('9', 'A Pagar'), ('7', 'A Enviar'), ('8', 'A Receber'), ('3', 'Concluído'), ('4', 'Cancelado')], max_length=1)),
                ('purchase_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('shopee_product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('shopee_product_variant', models.CharField(blank=True, max_length=255, null=True)),
                ('shopee_item_id', models.CharField(blank=True, max_length=70, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderPurchaseLineItems', to='shopee.order')),
                ('order_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrderPurchaseLineItems', to='shopee.orderpurchase')),
                ('user_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userShopOrderPurchaseLineItems', to='shopee.usershop')),
                ('user_shopee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrderPurchaseLineItems', to='shopee.usershopee')),
            ],
        ),
    ]
