# Generated by Django 3.1.3 on 2021-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0031_auto_20210114_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpurchase',
            old_name='shopee_list_type',
            new_name='list_type',
        ),
        migrations.RenameField(
            model_name='orderpurchaselineitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderpurchaselineitem',
            old_name='status',
            new_name='shopee_status',
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='canceled_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='shopee_item_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='shopee_order_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='shopee_original_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpurchaselineitem',
            name='shopee_item_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderpurchaselineitem',
            name='shopee_model_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderpurchaselineitem',
            name='shopee_shop_id',
            field=models.BigIntegerField(),
        ),
    ]
