# Generated by Django 3.1.3 on 2021-01-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0033_auto_20210116_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='order_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderLineItemOrderPurchaseLineItems', to='shopee.orderlineitem'),
        ),
    ]
