# Generated by Django 3.1.3 on 2021-01-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0034_orderpurchaselineitem_order_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AO', 'Aguardando Pedido'), ('AP', 'Aguardando Pagamento'), ('APS', 'Aguardando Pagamento Shopee'), ('AS', 'Aguardando Envio'), ('AF', 'Aguardando Processamento'), ('F', 'Processado'), ('C', 'Cancelado'), ('FO', 'Pedidos Falhadas')], max_length=3),
        ),
    ]
