# Generated by Django 3.1.3 on 2021-01-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0036_remove_orderpurchaselineitem_shopee_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='deactivate_status',
            field=models.CharField(blank=True, choices=[('IL', 'Login incorreto'), ('IP', 'Proxy incorreta'), ('IT', 'Token inválido'), ('TE', 'Erro ao finalizar transação'), ('M', 'Manual'), ('BA', 'Conta banida')], max_length=2),
        ),
    ]
