# Generated by Django 3.1.3 on 2021-01-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0038_auto_20210119_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershopee',
            name='created_on_shopee',
            field=models.BooleanField(default=False),
        ),
    ]
