# Generated by Django 3.1.3 on 2021-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0039_usershopee_created_on_shopee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershopee',
            name='created_on_shopee',
        ),
        migrations.AddField(
            model_name='usershopee',
            name='created_status',
            field=models.CharField(blank=True, choices=[('C', 'Created'), ('BC', 'Being Created'), ('NC', 'Not Created')], max_length=2),
        ),
    ]
