# Generated by Django 3.1.3 on 2021-01-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0040_auto_20210122_0628'),
        ('shopee', '0039_auto_20210122_1040'),
    ]

    operations = [
    ]
