# Generated by Django 3.1.3 on 2021-02-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0042_auto_20210123_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpurchase',
            name='shipping_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usershopee',
            name='captcha_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
