# Generated by Django 3.1.3 on 2021-02-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0043_auto_20210202_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='deactivate_status',
            field=models.CharField(blank=True, choices=[('IL', 'Login incorreto'), ('IP', 'Proxy incorreta'), ('IT', 'Token inválido'), ('TE', 'Erro ao finalizar transação'), ('M', 'Manual'), ('BA', 'Conta banida')], max_length=2, null=True),
        ),
    ]
