# Generated by Django 3.1.3 on 2021-02-04 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0044_auto_20210202_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dropshopee_created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
