# Generated by Django 3.1.3 on 2021-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0046_auto_20210210_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dropshopee_deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
