# Generated by Django 3.1.3 on 2021-02-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0048_auto_20210214_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
