# Generated by Django 3.1.3 on 2021-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0048_usershopee_creation_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_date_AF',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_AO',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_AP',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_APS',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_AS',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_C',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_F',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date_FO',
            field=models.DateTimeField(null=True),
        ),
    ]
