# Generated by Django 3.1.3 on 2021-02-14 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0048_usershopee_creation_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='last_products_sync_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='usershop',
            name='products_sync_requests',
            field=models.IntegerField(default=0),
        ),
    ]
