# Generated by Django 3.1.3 on 2021-02-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0049_auto_20210213_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_AF',
            new_name='updated_date_af',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_AO',
            new_name='updated_date_ao',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_AP',
            new_name='updated_date_ap',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_APS',
            new_name='updated_date_aps',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_AS',
            new_name='updated_date_as',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_C',
            new_name='updated_date_c',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_F',
            new_name='updated_date_f',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_date_FO',
            new_name='updated_date_fo',
        ),
    ]
