# Generated by Django 3.1.3 on 2021-02-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0049_auto_20210214_2328'),
        ('shopee', '0050_auto_20210214_2156'),
    ]

    operations = [
    ]
