# Generated by Django 3.1.3 on 2021-02-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0051_merge_20210215_2344'),
        ('shopee', '0049_auto_20210214_2146'),
        ('shopee', '0052_auto_20210215_2022'),
    ]

    operations = [
    ]
