# Generated by Django 3.1.3 on 2021-02-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0053_merge_20210216_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='PercentagePay',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('unpaid', 'Não Pago'), ('past_due', 'Pagamento atrasado')], max_length=10)),
                ('retry', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopee.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='percentage_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percentagePayOrders', to='shopee.percentagepay'),
        ),
    ]
