# Generated by Django 3.1.3 on 2021-02-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0054_auto_20210221_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagepay',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='percentagepay',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AO', 'Aguardando Pedido'), ('AP', 'Aguardando Pagamento'), ('APS', 'Aguardando Pagamento Fornecedor'), ('AS', 'Aguardando Envio'), ('AF', 'Aguardando Processamento'), ('F', 'Processado'), ('C', 'Cancelado'), ('FO', 'Pedidos Falhadas'), ('DO', 'Pedido Deletado')], max_length=3),
        ),
    ]
