# Generated by Django 3.1.3 on 2021-02-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0056_percentagepay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='percentage_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percentagePayOrderss', to='shopee.percentagepay'),
        ),
    ]
