# Generated by Django 3.1.3 on 2021-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0059_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
