# Generated by Django 3.1.3 on 2021-03-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0061_productvariant_inventory_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopifyVariants', to='shopee.productvariant'),
        ),
    ]
