# Generated by Django 3.1.3 on 2021-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0062_auto_20210307_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_number',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
