# Generated by Django 3.1.3 on 2021-03-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0064_auto_20210308_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershopee',
            name='last_purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
