# Generated by Django 3.1.3 on 2021-03-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0065_usershopee_last_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AO', 'Aguardando Pedido'), ('AP', 'Aguardando Pagamento'), ('APS', 'Aguardando Pagamento Fornecedor'), ('AS', 'Aguardando Envio'), ('AF', 'Aguardando Processamento'), ('F', 'Processado'), ('C', 'Cancelado'), ('FO', 'Pedidos Falhadas'), ('DO', 'Pedido Deletado'), ('AI', 'Aguardando Integração')], max_length=3),
        ),
    ]
