# Generated by Django 3.1.3 on 2021-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0066_auto_20210331_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_variant_id_text',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
