# Generated by Django 3.1.6 on 2021-04-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0068_orderraw_orderrawlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrawlineitem',
            name='product_variant_id_text',
        ),
    ]
