# Generated by Django 3.1.6 on 2021-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0069_remove_orderrawlineitem_product_variant_id_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_variant_id_text',
        ),
        migrations.AddField(
            model_name='orderrawlineitem',
            name='product_variant_id_text',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
