# Generated by Django 3.1.6 on 2021-04-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0070_auto_20210404_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrawlineitem',
            name='product_variant_id_text',
        ),
    ]
