# Generated by Django 3.1.6 on 2021-04-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0072_auto_20210404_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderraw',
            name='financial_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderraw',
            name='fulfillment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderraw',
            name='gateway',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
