# Generated by Django 3.1.6 on 2021-04-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0073_auto_20210405_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderraw',
            name='value',
        ),
    ]
