# Generated by Django 3.1.6 on 2021-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0074_remove_orderraw_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderraw',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
