# Generated by Django 3.1.6 on 2021-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0075_orderraw_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='warrantyProduct',
            field=models.BooleanField(default=False),
        ),
    ]
