# Generated by Django 3.1.6 on 2021-04-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0076_productvariant_warrantyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='warrantyProduct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
