# Generated by Django 3.1.6 on 2021-04-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0077_auto_20210407_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='warrantyProduct',
            new_name='warranty_product',
        ),
    ]
