# Generated by Django 3.1.6 on 2021-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0078_auto_20210407_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='warranty_product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_processable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
