# Generated by Django 3.1.6 on 2021-04-08 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0079_auto_20210407_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagepay',
            name='last_manual_pay_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='percentagepay',
            name='manual_pay_requests',
            field=models.IntegerField(default=0),
        ),
    ]
