# Generated by Django 3.1.6 on 2021-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0080_auto_20210408_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentagepay',
            name='manual_pay_requests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
