# Generated by Django 3.1.6 on 2021-04-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0081_auto_20210409_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_processable',
        ),
    ]
