# Generated by Django 3.1.6 on 2021-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0082_remove_productvariant_is_processable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_processable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
