# Generated by Django 3.1.6 on 2021-04-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0084_orderpurchase_shopee_order_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpurchase',
            name='shopee_order_sn',
        ),
    ]
