# Generated by Django 3.1.3 on 2021-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0085_remove_orderpurchase_shopee_order_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_processable',
            field=models.BooleanField(default=True),
        ),
    ]
