# Generated by Django 3.1.3 on 2021-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0086_auto_20210420_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='users_without_valid_voucher',
            field=models.TextField(null=True),
        ),
    ]
