# Generated by Django 3.1.6 on 2021-06-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0087_auto_20210605_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hasChild',
            new_name='has_child',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='parentOrder',
            new_name='parent_order',
        ),
    ]
