# Generated by Django 3.1.3 on 2021-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0087_auto_20210531_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='captcha_signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
