# Generated by Django 3.1.3 on 2021-06-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0088_auto_20210605_1850'),
        ('shopee', '0087_order_users_without_valid_voucher'),
    ]

    operations = [
    ]
