# Generated by Django 3.1.3 on 2021-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0089_auto_20210601_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershopee',
            name='spc_ec',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usershopee',
            name='created_status',
            field=models.CharField(blank=True, choices=[('C', 'Created'), ('BC', 'Being Created'), ('NC', 'Not Created'), ('ENV', 'Email not validated'), ('TNV', 'Telephone not validated')], max_length=3),
        ),
        migrations.AlterField(
            model_name='usershopee',
            name='spc_f',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
