# Generated by Django 3.1.3 on 2021-06-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0091_usershopee_identity_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershopee',
            name='spc_ec',
        ),
    ]
