# Generated by Django 3.1.3 on 2021-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0092_remove_usershopee_spc_ec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
