# Generated by Django 3.1.3 on 2021-06-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0093_auto_20210602_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
