# Generated by Django 3.1.3 on 2021-07-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0089_merge_20210619_0014'),
        ('shopee', '0095_usershopee_spc_ec'),
    ]

    operations = [
    ]
