# Generated by Django 3.1.3 on 2021-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0098_usershop_notify_order_fulfillment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(help_text='Descrição sobre o alerta (aceita HTML).')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('secondary', 'Cinza'), ('success', 'Verde'), ('danger', 'Vermelho'), ('warning', 'Amarelo'), ('info', 'Ciano'), ('dark', 'Preto'), ('white', 'Branco')], default='info', max_length=9)),
                ('active', models.BooleanField(default=True, help_text='Mostra o alerta ou não.')),
                ('expires_in', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
