# Generated by Django 3.1.3 on 2021-08-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0098_usershop_notify_order_fulfillment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershopee',
            name='deactivate_status',
            field=models.CharField(blank=True, choices=[('IL', 'Login incorreto'), ('IP', 'Proxy incorreta'), ('IT', 'Token inválido'), ('TE', 'Erro ao finalizar transação'), ('M', 'Manual'), ('BA', 'Conta banida'), ('EL', 'Login expirou')], default='', max_length=2),
        ),
    ]
