# Generated by Django 3.1.3 on 2021-08-23 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopee', '0099_auto_20210811_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=5)),
                ('cnpj', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True)),
                ('cpf', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=85)),
                ('state', models.CharField(max_length=85)),
                ('phone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
