# Generated by Django 3.1.3 on 2021-08-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0099_news_usernewsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='icon',
            field=models.CharField(default='star', help_text='https://feathericons.com', max_length=15),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, help_text='Opcional.'),
        ),
    ]
