# Generated by Django 3.1.3 on 2021-08-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0100_auto_20210803_1855'),
        ('shopee', '0099_alert'),
    ]

    operations = [
    ]
