# Generated by Django 3.1.3 on 2021-08-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0100_userbillingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbillingdata',
            name='address2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
