# Generated by Django 3.1.3 on 2021-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0101_merge_20210811_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='expires_in',
            field=models.DateField(help_text='Dias até o alerta expirar.'),
        ),
    ]
