# Generated by Django 3.1.3 on 2021-08-24 20:00

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0101_auto_20210823_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbillingdata',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userbillingdata',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True),
        ),
    ]
