# Generated by Django 3.1.3 on 2021-08-11 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0102_auto_20210811_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='alert',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 18, 56, 33, 891704, tzinfo=utc), help_text='Dia em que o alerta deixará de aparecer.'),
            preserve_default=False,
        ),
    ]
