# Generated by Django 3.1.6 on 2021-08-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0099_auto_20210810_2255'),
        ('shopee', '0103_auto_20210811_1556'),
    ]

    operations = [
    ]
