# Generated by Django 3.1.3 on 2021-08-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0102_auto_20210824_1700'),
        ('shopee', '0104_merge_20210818_0142'),
    ]

    operations = [
    ]
