# Generated by Django 3.1.3 on 2021-08-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0106_userbillingdata_address_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userbillingdata',
            name='address_number',
            field=models.CharField(default='', max_length=6),
        ),
    ]
