# Generated by Django 3.1.3 on 2021-09-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0107_auto_20210825_1923'),
        ('shopee', '0105_auto_20210819_1524'),
    ]

    operations = [
    ]
