# Generated by Django 3.1.3 on 2021-12-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0108_merge_20210909_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershopee',
            name='device_sz_fingerprint',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
