# Generated by Django 3.1.3 on 2021-11-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0108_merge_20210909_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_cancel_request_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
