# Generated by Django 3.1.3 on 2021-09-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0108_merge_20210909_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productshopee',
            name='error',
        ),
        migrations.AlterField(
            model_name='orderpurchaselineitem',
            name='shopee_model_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productshopee',
            name='model_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]