# Generated by Django 3.1.3 on 2021-10-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0108_merge_20210909_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]