# Generated by Django 3.1.3 on 2021-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0108_merge_20210909_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dropshipping_xp_time',
            field=models.CharField(blank=True, choices=[('ONE_TO_THREE_MONTH', '1 a 3 meses'), ('THREE_TO_SIX_MONTH', '3 a 6 meses'), ('SIX_TO_TWELVE_MONTH', '6 a 12 meses'), ('MORE_THAN_TWELVE_MONTH', 'Mais de 12 meses')], max_length=50, null=True),
        ),
    ]
