# Generated by Django 3.1.3 on 2021-11-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0109_auto_20210920_1608'),
        ('shopee', '0109_auto_20210915_1936'),
        ('shopee', '0109_auto_20211014_1725'),
    ]

    operations = [
    ]
