# Generated by Django 3.1.3 on 2021-11-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0110_merge_20211118_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1750)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('vendor', models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='droplinkfy_created_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='droplinkfy_deleted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='percentage_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percentagePayOrdersLineItem', to='shopee.percentagepay'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('AO', 'Aguardando Pedido'), ('AP', 'Aguardando Pagamento'), ('APS', 'Aguardando Pagamento Fornecedor'), ('AS', 'Aguardando Envio'), ('AF', 'Aguardando Processamento'), ('F', 'Processado'), ('C', 'Cancelado'), ('FO', 'Pedidos Falhadas'), ('DO', 'Pedido Deletado'), ('AI', 'Aguardando Integração')], default='AI', max_length=3),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='sync_shopee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_af',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_ao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_ap',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_aps',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_as',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_c',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_f',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='updated_date_fo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='user_shopee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userShopeeOrdersLineItem', to='shopee.usershopee'),
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='vendor',
            field=models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=25),
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='product_image',
            field=models.URLField(blank=True, default=None, max_length=1750, null=True),
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='vendor',
            field=models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=25),
        ),
        migrations.AddField(
            model_name='productshopee',
            name='vendor',
            field=models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=25),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vendor',
            field=models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=15),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='order_memo',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='usershopee',
            name='vendor',
            field=models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=15),
        ),
        migrations.AddField(
            model_name='orderpurchase',
            name='boleto_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopee.boleto'),
        ),
        migrations.AddField(
            model_name='orderpurchaselineitem',
            name='carrier_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopee.carrier'),
        ),
        migrations.AddField(
            model_name='productshopee',
            name='carrier_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopee.carrier'),
        ),
    ]
