# Generated by Django 3.1.3 on 2021-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0110_merge_20211118_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='cancellation_status',
            field=models.CharField(choices=[('NC', 'Não cancelado'), ('WC', 'A cancelar'), ('C', 'Cancelado')], default='NC', max_length=2),
        ),
    ]
