# Generated by Django 3.1.3 on 2021-12-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0111_orderlineitem_cancellation_status'),
        ('shopee', '0111_auto_20211118_1715'),
    ]

    operations = [
    ]
