# Generated by Django 3.1.3 on 2021-12-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0111_orderlineitem_cancellation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='vendor',
            field=models.CharField(choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderpurchaselineitem',
            name='shopee_shop_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productshopee',
            name='shop_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
