# Generated by Django 3.1.3 on 2021-12-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0112_merge_20211213_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='error',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='error_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='shopee_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderpurchaselineitem',
            name='shopee_shop_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productshopee',
            name='shop_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
