# Generated by Django 3.1.3 on 2022-01-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0113_usershopee_banned_at'),
        ('shopee', '0109_auto_20211125_1850'),
        ('shopee', '0113_auto_20211213_2326'),
    ]

    operations = [
    ]
