# Generated by Django 3.1.3 on 2022-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0114_merge_20220103_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='vendor',
            field=models.CharField(blank=True, choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usershopee',
            name='created_status',
            field=models.CharField(blank=True, choices=[('C', 'Created'), ('BC', 'Being Created'), ('NC', 'Not Created'), ('ENV', 'Email not validated'), ('EAR', 'Email already exists'), ('TNV', 'Telephone not validated')], max_length=3),
        ),
    ]
