# Generated by Django 3.1.3 on 2022-01-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0111_profile_dropshipping_xp_time'),
        ('shopee', '0115_auto_20220103_1808'),
    ]

    operations = [
    ]
