# Generated by Django 3.1.3 on 2022-01-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0112_auto_20211222_1846'),
        ('shopee', '0109_auto_20211124_1433'),
        ('shopee', '0117_auto_20220104_1003'),
    ]

    operations = [
    ]
