# Generated by Django 3.1.3 on 2022-01-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0118_merge_20220113_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='vendor',
            field=models.CharField(blank=True, choices=[('shopee', 'shopee'), ('ali', 'ali')], default='shopee', max_length=25, null=True),
        ),
    ]
