# Generated by Django 3.1.3 on 2022-01-27 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0120_boleto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
