# Generated by Django 3.1.3 on 2022-02-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0122_ordererrorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordererrorlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
