# Generated by Django 3.1.3 on 2022-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0123_auto_20220217_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordererrorlog',
            name='traceback_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
